FROM rocker/binder:4.1.2

# Installing CS-jupyterlab-grdm https://github.com/RCOSDP/CS-rstudio-grdm/
RUN R -e 'devtools::install_github("yacchin1205/CS-rstudio-grdm", ref = "fix/default-storage-provider", type = "source")';
